### PR TITLE
New ADRs

### LINKED ISSUE #125: Create ADR for how components vs atoms are handled + wiki/readme

### PR DESCRIPTION
**Pull request by raggeju**
Closes #125 & #135

### CODE REVIEW

**Comment by tobiasljungstrom** [comment]
Well written. There is a thought I've been having regarding the naming though. I wonder if maybe there is a better name than atoms. Since this alludes in a very strong way towards Atomic design it might confuse people. For instance, according to Atomic design, a button is an atom, but we don't call button an atom, we call it a component, since we export it as a primary component in the library.

Maybe we should call them **components** (our primary, marketed components) and **sub-components** (building blocks of the primary components).

What do you think?

**Comment by raggeju** [comment]
> Well written. There is a thought I've been having regarding the naming though. I wonder if maybe there is a better name than atoms. Since this alludes in a very strong way towards Atomic design it might confuse people. For instance, according to Atomic design, a button is an atom, but we don't call button an atom, we call it a component, since we export it as a primary component in the library.
> 
> Maybe we should call them **components** (our primary, marketed components) and **sub-components** (building blocks of the primary components).
> 
> What do you think?

I really like the idea! Maybe we should discuss this further in a meeting/daily? I will mark both ADRs "proposed" for now and we can come back and change them later? What do you think?

**Comment by PatrikAnderssonCybercom** [comment]
I think 

> > Well written. There is a thought I've been having regarding the naming though. I wonder if maybe there is a better name than atoms. Since this alludes in a very strong way towards Atomic design it might confuse people. For instance, according to Atomic design, a button is an atom, but we don't call button an atom, we call it a component, since we export it as a primary component in the library.
> > Maybe we should call them **components** (our primary, marketed components) and **sub-components** (building blocks of the primary components).
> > What do you think?
> 
> I really like the idea! Maybe we should discuss this further in a meeting/daily? I will mark both ADRs "proposed" for now and we can come back and change them later? What do you think?

I think that's a good idea. I've been questioning the use of terms like "Atom" when it's not being used as intended, and will almost certainly cause some sort of confusion down the line.

**Review by tobiasljungstrom — APPROVED** [review]
I'll approve these as proposed and then we can discuss it live tomorrow. :)

**Comment by raggeju** [comment]
> I think
> 
> > > Well written. There is a thought I've been having regarding the naming though. I wonder if maybe there is a better name than atoms. Since this alludes in a very strong way towards Atomic design it might confuse people. For instance, according to Atomic design, a button is an atom, but we don't call button an atom, we call it a component, since we export it as a primary component in the library.
> > > Maybe we should call them **components** (our primary, marketed components) and **sub-components** (building blocks of the primary components).
> > > What do you think?
> > 
> > 
> > I really like the idea! Maybe we should discuss this further in a meeting/daily? I will mark both ADRs "proposed" for now and we can come back and change them later? What do you think?
> 
> I think that's a good idea. I've been questioning the use of terms like "Atom" when it's not being used as intended, and will almost certainly cause some sort of confusion down the line. Maybe sub-component is a good alternative, or "bits" or "partial" or simply switching over to actual atomic design best practice.

As mentioned here we should discuss these matters in a live session. Lets try to do it tomorrow morning.

**Pull request merged**
